spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: catewha2022
    url: jdbc:mariadb://cat-database.ccmo8onyohgn.ap-northeast-2.rds.amazonaws.com:3306/cat_database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      enabled: 'true'
      location: C:\\temp\\upload
      max-file-size: 10MB
      max-request-size: 30MB


logging:
  level:
    org:
      springframework:
        nodeValue: debug
        web: debug
      hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

app:
  auth:
    tokenSecret: jwtsecretkeyofcatbackendfromewha
    tokenExpiry: 1800000