
cloud:
  aws:
    s3:
      bucket: cat-imagebucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAS3ERHOZ4SMJTQI65
      secretKey: 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
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB