spring:
  profiles:
    include: aws
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: catewha2022
    url: jdbc:mariadb://cat-database.ccmo8onyohgn.ap-northeast-2.rds.amazonaws.com:3306/cat_database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org:
      springframework:
        nodeValue: debug
        web: debug
      hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

app:
  auth:
    tokenSecret: jwtsecretkeyofcatbackendfromewha
    tokenExpiry: 3600000

server:
  ssl:
    key-store: classpath:cat-keystore.p12
    key-store-type: PKCS12
    key-store-password: catewha2022
    key-alias: cat-keystore
    enabled: true